### PR TITLE
Fix test suite usage

### PR DESCRIPTION
**Pull request by johanneskoester**

### CODE REVIEW

**Comment by vsoch** [comment]
Added you as maintainer (so it should not need to get permission to run)!

**Comment by vsoch** [comment]
Merged in https://github.com/rse-ops/snakemake-executor-plugin-googlebatch/pull/7 with linting fixes.

**Comment by vsoch** [comment]
@johanneskoester my question is how do I use this (for local testing) outside of this test case?

**Comment by johanneskoester** [comment]
The equivalent for manual testing ist `--default-storage-provider s3 --default-storage-prefix $SOMEPREFIX --storage-s3-endpoint-url https://play.minio.io:9000 --storage-s3-access-key Q3AM3UQ867SPQQA43P2F --storage-s3-secret-key zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG`. With `$SOMEPREFIX` being something unique  that you can later delete. Note that it has to be a valid s3 uri, i.e. `"s3://snakemake-test-googlebatch/"`.

**Comment by vsoch** [comment]
Will try this tomorrow (going to bed now!)

**Pull request closed without merging**
